version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
