---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
inputs:
- name: pre-release
- name: broker-pak
- name: version
params:
  ARM_SUBSCRIPTION_ID: 
  ARM_TENANT_ID:
  ARM_CLIENT_ID:
  ARM_CLIENT_SECRET:
run:
  path: /bin/bash
  args:    
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      
outputs:
  - name: build
    path: cloud-service-broker/build