---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
inputs:
- name: brokerbuild
- name: brokerpak
run:
  path: /bin/bash
  args:    
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      export DB_USERNAME=root
      export DB_PASSWORD=brokerpass
      export DB_NAME=servicebroker

      docker run --rm --network host --name test-mysql -e MYSQL_ROOT_PASSWORD=${DB_PASSWORD} -e MYSQL_DATABASE="${DB_NAME}" -d mysql:5.7
      sleep 45
      export PORT=8080
      export GSB_BROKERPAK_BUILTIN_PATH=brokerpak
      export DB_HOST=localhost
      ./brokerbuild/cloud-service-broker.linux serve &
      sleep 5
      ./brokerbuild/cloud-service-broker.linux client run-examples

