---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
params:
  SERVICE_NAME:
  GSB_BROKERPAK_BUILTIN_PATH:
  PARALLEL_JOB_COUNT: 1
inputs:
- name: brokerbuild
run:
  path: /bin/bash
  args:    
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      export DB_USERNAME=root
      export DB_PASSWORD=brokerpass
      export DB_NAME=servicebroker

      docker run --rm --network host --name test-mysql -e MYSQL_ROOT_PASSWORD=${DB_PASSWORD} -e MYSQL_DATABASE="${DB_NAME}" -d mysql:5.7
      sleep 45
      export PORT=8080
      export DB_HOST=localhost
      ./brokerbuild/build/cloud-service-broker.linux serve &
      sleep 10
      if [ -z "$SERVICE_NAME" ]; then
        ./brokerbuild/build/cloud-service-broker.linux client run-examples -j "${PARALLEL_JOB_COUNT}"
      else
        ./brokerbuild/build/cloud-service-broker.linux client run-examples --service-name "${SERVICE_NAME}" -j "${PARALLEL_JOB_COUNT}"
      fi

