---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
inputs:
- name: release
- name: broker-pak
- name: version
params:
  ARM_SUBSCRIPTION_ID: 
  ARM_TENANT_ID:
  ARM_CLIENT_ID:
  ARM_CLIENT_SECRET:
run:
  path: /bin/bash
  args:    
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      export DB_USERNAME=root
      export DB_PASSWORD=brokerpass
      export DB_NAME=servicebroker

      docker run --rm -p 3306:3306 --name test-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE="${DB_NAME}" -d mysql:5.7
      sleep 60
      chmod +x release/cloud-service-broker.linux
      export PORT=8080
      export GSB_BROKERPAK_BUILTIN_PATH=broker-pak
      export DB_HOST=127.0.0.1
      ./release/cloud-service-broker.linux serve &
      sleep 5
      ./release/cloud-service-broker.linux client run-examples

