---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.13"
inputs:
- name: pre-release
- name: broker-pak
- name: version
run:
  dir: cloud-service-broker
  path: /bin/bash
  args:    
    - -exc
    - |
      ls pre-release
      ls broker-pak
      ls version
outputs:
  - name: build
    path: cloud-service-broker/build