---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: release
- name: broker-pak
run:
  dir: broker-pak
  path: release/cloud-service-broker.linux
  args: ["pak", "build"]   
