---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.13"
inputs:
- name: release
- name: broker-pak
- name: version
params:
  BROKERPAKDIR:
run:
  dir: broker-pak
  path: /bin/bash
  args: 
  - -exc
  - |
    chmod +x ../release/cloud-service-broker.linux
    export VERSION=$(cat ../version/version)
    cd ${BROKERPAKDIR}
    sed -i .bak "s/^version:.*/version: ${VERSION}/" manifest.yml
    ../../release/cloud-service-broker.linux pak build  
outputs:
- name: brokerpak-dir
  path: broker-pak/$BROKERPAKDIR
