---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: release
- name: broker-pak
run:
  dir: broker-pak
  path: /bin/bash
  args: 
  - -exc
  - |
    chmod +x ../release/cloud-service-broker.linux
    ../release/cloud-service-broker.linux pak build   
