---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/tile-generator

inputs:
- name: gcp-service-broker-ci
- name: gcp-service-broker
  path: src/gcp-service-broker

outputs:
- name: candidate

run:
  path: gcp-service-broker-ci/ci/tasks/build-tile.sh