---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/tile-generator
    tag: latest
inputs:
- name: cloud-service-broker-ci
- name: cloud-service-broker
  path: src/cloud-service-broker
- name: metadata

outputs:
- name: tiles

run:
  path: cloud-service-broker-ci/ci/tasks/build-tile.sh
