---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest
inputs:
- name: release
- name: broker-pak
- name: version
params:
  BROKERPAKDIR:
run:
  dir: broker-pak
  path: /bin/bash
  args: 
  - -exc
  - |
    chmod +x ../release/cloud-service-broker.linux
    export VERSION=$(cat ../version/version)
    cd ${BROKERPAKDIR}
    mv manifest.yml manifest.yml.orig
    sed "s/^version:.*/version: ${VERSION}/" < manifest.yml.orig > manifest.yml
    lsb_release  -a
    ../../release/cloud-service-broker.linux pak build  
outputs:
- name: brokerpak-dir
  path: broker-pak/$BROKERPAKDIR
