---
platform: linux
inputs:
- name: release
- name: broker-pak
- name: version
params:
  BROKERPAKDIR:
run:
  dir: broker-pak
  path: /bin/sh
  args: 
  - -exc
  - |
    chmod +x ../release/cloud-service-broker.linux
    cp ../release/cloud-service-broker.linux ${BROKERPAKDIR}/cloud-service-broker
    export VERSION=$(cat ../version/version)
    cd ${BROKERPAKDIR}
    mv manifest.yml manifest.yml.orig
    sed "s/^version:.*/version: ${VERSION}/" < manifest.yml.orig > manifest.yml
    ls -al .
    ./cloud-service-broker pak build  
outputs:
- name: brokerpak-dir
  path: broker-pak/$BROKERPAKDIR
