---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: release
- name: broker-pak
- name: version
params:
  BROKERPAKDIR:
run:
  dir: broker-pak
  path: /bin/sh
  args: 
  - -exc
  - |
    chmod +x ../release/cloud-service-broker.linux
    ls -al ../release
    export VERSION=$(cat ../version/version)
    cd ${BROKERPAKDIR}
    mv manifest.yml manifest.yml.orig
    sed "s/^version:.*/version: ${VERSION}/" < manifest.yml.orig > manifest.yml
    ls ..
    ls ../..
    ls -al ../../release    
    ../../release/cloud-service-broker.linux pak build  
outputs:
- name: brokerpak-dir
  path: broker-pak/$BROKERPAKDIR
