---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.13"
inputs:
- name: cloud-service-broker
  path: broker-source
- name: version
run:
  dir: broker-source
  path: /bin/bash
  args:    
    - -exc
    - |
      export VERSION=$(cat version/version)
      make build
