---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.13"
inputs:
- name: cloud-service-broker
  path: src
run:
  dir: src
  path: make
  args: ['test-units']
