---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: gcp-service-broker-ci
- name: gcp-service-broker
  path: src/gcp-service-broker

params:
  ROOT_SERVICE_ACCOUNT_JSON:
  TEST_DB_USERNAME:
  TEST_DB_PASSWORD:

run:
  path: gcp-service-broker-ci/ci/tasks/integration-tests.sh