---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: cloud-service-broker
- name: cloud-service-broker-ci
- name: compiled-broker
outputs:
- name: metadata
run:
  path: cloud-service-broker-ci/ci/tasks/metadata.sh
