---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: compiled-broker
- name: cloud-service-broker-ci

params:
  ROOT_SERVICE_ACCOUNT_JSON:
  DB_USERNAME:
  DB_PASSWORD:
  DB_HOST:
  CA_CERT:
  CLIENT_CERT:
  CLIENT_KEY:
run:
  path: cloud-service-broker-ci/ci/tasks/osb-integration-tests.sh
