---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: gcp-service-broker-ci
- name: gcp-service-broker
  path: src/gcp-service-broker

params:
  ROOT_SERVICE_ACCOUNT_JSON:
  DB_USERNAME:
  DB_PASSWORD:
  DB_HOST:

run:
  path: gcp-service-broker-ci/ci/tasks/osb-integration-tests.sh
