---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: gcp-service-broker
  path: src/gcp-service-broker

run:
  path: src/gcp-service-broker/ci/tasks/unit-tests.sh