---
resources:
- name: cloud-service-broker
  type: git
  source:
    uri: https://github.com/pivotal/cloud-service-broker
    branch: master
    password: ((cf-pe-bot-repo-key))
    username: cf-pe-bot
    ignore_paths:
      - aws-brokerpak/*
      - azure-brokerpak/*
      - gcp-brokerpak/*

jobs:
  - name: unit-test
    plan:
      - get: cloud-service-broker
        trigger: true
      - task: test
        file: cloud-service-broker/ci/tasks/go-test.yml


