---
resources:
  - name: gcp-service-broker
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: concourse
      ignore_paths:
        - product/
        - release/

jobs:
  - name: test-unit
    plan:
      - get: gcp-service-broker
        trigger: true
      - task: unit-tests
        file: gcp-service-broker/ci/tasks/unit-tests.yml
  - name: build-tile
    plan:
      - get: gcp-service-broker
        trigger: true
      - task: build-tile
        file: gcp-service-broker/ci/tasks/build-tile.yml