---
resources:
  - name: gcp-service-broker
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: concourse
      ignore_paths:
        - ci/*

  - name: gcp-service-broker-ci
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: concourse
      paths:
        - ci/*

jobs:
  - name: test-unit
    plan:
      - get: gcp-service-broker
        trigger: true
      - get: gcp-service-broker-ci
      - task: unit-tests
        file: gcp-service-broker-ci/ci/tasks/unit-tests.yml

  - name: integration
    plan:
      - get: gcp-service-broker
        trigger: true
        passed: [test-unit]
      - get: gcp-service-broker-ci
      - task: integration-tests
        file: gcp-service-broker-ci/ci/tasks/integration-tests.yml
        params:
          ROOT_SERVICE_ACCOUNT_JSON: {{service_account_key}}

  - name: build-tile
    plan:
      - get: gcp-service-broker
        trigger: true
        passed: [integration]
      - get: gcp-service-broker-ci
      - task: build-tile
        file: gcp-service-broker-ci/ci/tasks/build-tile.yml