---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gcp-service-broker
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: concourse
      ignore_paths:
        - ci/*

  - name: gcp-service-broker-ci
    type: git
    source:
      uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
      branch: concourse
      paths:
        - ci/*

  - name: release
    type: gcs-resource
    source:
      bucket: gcp-service-broker-tiles
      json_key: {{STORAGE_BUCKET_KEY}}
      regexp: gcp-service-broker-(.*).pivotal

  - name: release-rc
    type: gcs-resource
    source:
      bucket: gcp-service-broker-tiles
      json_key: {{STORAGE_BUCKET_KEY}}
      regexp: gcp-service-broker-(.*).pivotal

  - name: version
    type: semver
    source:
      bucket: gcp-service-broker-semver
      key: semver
      endpoint: storage.googleapis.com
      access_key_id: {{storage_key_id}}
      secret_access_key: {{storage_secret_key}}
      initial_version: 3.1.3

  - name: release-version
    type: semver
    source:
      bucket: gcp-service-broker-semver
      key: release-semver
      endpoint: storage.googleapis.com
      access_key_id: {{storage_key_id}}
      secret_access_key: {{storage_secret_key}}
      initial_version: 3.1.3

jobs:
  - name: test-unit
    plan:
      - aggregate:
        - get: gcp-service-broker
          trigger: true
        - get: gcp-service-broker-ci
      - task: unit-tests
        file: gcp-service-broker-ci/ci/tasks/unit-tests.yml

  - name: integration
    plan:
      - aggregate:
        - get: gcp-service-broker
          trigger: true
        - get: gcp-service-broker-ci
      - task: integration-tests
        file: gcp-service-broker-ci/ci/tasks/integration-tests.yml
        params:
          ROOT_SERVICE_ACCOUNT_JSON: {{service_account_key}}
          TEST_DB_USERNAME: {{TEST_DB_USERNAME}}
          TEST_DB_PASSWORD: {{TEST_DB_PASSWORD}}
          TEST_DB_HOST: {{TEST_DB_HOST}}

  - name: build-test-tile
    plan:
      - aggregate:
        - get: version
          params: {bump: patch, pre: rc}
        - get: gcp-service-broker
          trigger: true
          passed: [test-unit, integration]
        - get: gcp-service-broker-ci
      - task: build-tile
        file: gcp-service-broker-ci/ci/tasks/build-tile.yml
      - put: release-rc
        params:
          file: candidate/gcp-service-broker-*.pivotal
      - put: version
        params: {file: version/version}

  - name: ship-tile
    plan:
      - aggregate:
        - get: release-version
          params: {bump: final}
          trigger: true
        - get: gcp-service-broker
          passed: [build-test-tile]
        - get: gcp-service-broker-ci
      - task: ship-tile
        file: gcp-service-broker-ci/ci/tasks/ship-tile.yml
      - put: release
        params:
          file: candidate/gcp-service-broker-*.pivotal



  - name: major
    public: true
    serial_groups: [release-version]
    plan:
    - get: release-version
      params: {bump: major, pre: rc}
    - get: gcp-service-broker
    - put: release-version
      params: {file: release-version/version}

  - name: minor
    public: true
    serial_groups: [release-version]
    plan:
    - get: release-version
      params: {bump: minor, pre: rc}
    - get: gcp-service-broker
    - put: release-version
      params: {file: release-version/version}

  - name: patch
    public: true
    serial_groups: [release-version]
    plan:
    - get: release-version
      params: {bump: patch, pre: rc}
    - get: gcp-service-broker
    - put: release-version
      params: {file: release-version/version}
